package com.fiap.postech.fase3.Parquimetro.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.br.CPF;
import org.springframework.data.mongodb.core.mapping.DBRef;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Condutor")
public class Condutor {
    @CPF
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String condutor_CPF;
    @DynamoDBAttribute
    private String nome;
    @DynamoDBAttribute
    private String rua;
    @DynamoDBAttribute
    private int endereco_numero;
    @DynamoDBAttribute
    private String cidade;
    @DynamoDBAttribute
    private String bairro;
    @DynamoDBAttribute
    private String estado;
    @DynamoDBAttribute
    private String celular;
}
