package com.fiap.postech.fase3.Parquimetro.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fiap.postech.fase3.Parquimetro.model.converter.LocalDateTimeConverter;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jdk.jfr.DataAmount;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@AllArgsConstructor
@Data
@DynamoDBDocument
public class Estacionamento {
    public Estacionamento(){

    }
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    @NotNull(message = "O atributo CPF é obrigatório!")
    private String condutor_CPF;
    @NotNull(message = "O atributo placa é obrigatório!")
    @DynamoDBAttribute
    private String placa;
    @NotNull(message = "O atributo opção tempo fixo/hora é obrigatório!")
    @DynamoDBAttribute
    private boolean flagTempoFixoHora;
    @Min(value = 1, message = "O tempo mínimo de estacionamento é de uma hora!")
    @DynamoDBAttribute
    private int duracaoEstacionamento;
    @DynamoDBAttribute
    @DynamoDBTypeConverted( converter = LocalDateTimeConverter.class )
    private LocalDateTime inicioEstacionamento;


}
