package com.fiap.postech.fase3.Parquimetro.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jdk.jfr.DataAmount;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@AllArgsConstructor
@Data
@DynamoDBDocument
public class Estacionamento {
    public Estacionamento(){

    }
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    private String condutor_CPF;
    @DynamoDBAttribute
    private String placa;
    @DynamoDBAttribute
    private boolean flagTempoFixoHora;
    @DynamoDBAttribute
    private int duracaoEstacionamento;
    @DynamoDBAttribute
    private LocalDateTime inicioEstacionamento;


}
