package com.fiap.postech.fase3.Parquimetro.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.DBRef;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Forma_Pagamento")
public class Forma_Pagamento {

    private String condutor_CPF;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String chave_forma_pagamento;

    @DynamoDBAttribute
    private String numero_cartao;

    @DynamoDBAttribute
    private boolean flag_credito_debito;

    @DynamoDBAttribute
    private LocalDateTime data_validade;

    @DynamoDBAttribute
    private Integer cvv;

    @DynamoDBAttribute
    public String chave_PIX;
}

