package com.fiap.postech.fase3.Parquimetro.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.br.CPF;

import java.util.List;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Condutor")
public class Veiculo {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    @NotNull(message = "O atributo placa é obrigatório!")
    private String placa;
    @DynamoDBAttribute
    @NotNull(message = "O atributo modelo é obrigatório!")
    private String modelo;
    @DynamoDBAttribute
    @NotNull(message = "O atributo ano é obrigatório!")
    private String ano;
}
